
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/nfree/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
...
